### ISSUE TITLE
BCC_OK State no llread a causar estragos no llclose()

### ISSUE THREAD

**Issue by filiperecharte** [Ca-moes/RCOM#31]
Basicamente tentei enviar o pinguim.gif, e ele não consegue fechar tudo direito.

Fiz debug e o que está a acontecer é:
Por alguma razão a variavel frame `unsigned char frame[MAX_SIZE+6]; /*Trama*/` na struct linkLayer está a ficar sem espaço e está a afetar a variável `unsigned int status; /*TRANSMITTER | RECEIVER*/` fazendo com que ela fique com lixo.

variavel status da struct linklayer:
"STATUSS" antes de correr a máquina de estados e "status2" depois de correr a maquina de estados:
![Screenshot from 2020-10-25 02-54-09](https://user-images.githubusercontent.com/52135958/97097811-5f3cd280-166d-11eb-99be-0e5ebc43a79d.png)
o que faz com que o receiver chegue ao fim e *não* corra o llclose :-)

Isto acontece ao preencher o frame na maquina de estados do llread:
`if (state_machine.type == Read) linkLayer.frame[frameIndex] = byte;`
E acontece logo com o primeiro frame.

a 7 bytes do fim da trama I, ou seja se adicionarmos 7 ao tamanho do frame buffer corre tudo muito bem - temos de descobrir pq é q ele está a usar mais 7bytes do que é suposto

O pior é que só acontece com este ficheiro, experimentei com um ficheiro de texto com bué caracteres e funcionou bem.  lets see

**Comment by Ca-moes** [comment]
Acho que entendi o que se está a passar, mas parece muito esquisito. Não entendi a parte de "a 7 bytes do fim da trama I".
2 coisas que acho que podemos ter em conta:
- no `llread()` podemos substituir `unsigned char *dataBuf;` por `unsigned char dataBuf[MAX_SIZE];` agora que decidimos que `MAX_SIZE` é o tamanho máximo dos dados nas tramas I AKA tamanho máximo de um pacote de dados.
-  Em `pla.h` trocar a ordem das variaveis da `struct linkLayer` para pôr o `unsigned char frame[MAX_SIZE+6]; /*Trama*/` no fim
```c
struct linkLayer {
  char port[20]; /*Dispositivo /dev/ttySx, x = 0, 1*/
  int baudRate; /*Velocidade de transmissão*/
  unsigned char sequenceNumber;   /*Número de sequência da trama: 0x00, 0x01*/
  unsigned int timeout; /*Valor do temporizador: 1 s*/
  unsigned int numTransmissions; /*Número de tentativas em caso defalha*/
  unsigned int status; /*TRANSMITTER | RECEIVER*/
  unsigned char frame[MAX_SIZE+6]; /*Trama*/
};
```
Para o caso do problemas ser relativo ao padding

**Comment by filiperecharte** [comment]
solved: trocou-se a ordem das variaveis da struct linkLayer para pôr o unsigned char frame[MAX_SIZE+6]; /*Trama*/ no fim 

problema relativo ao padding
