### ISSUE TITLE
Verificar numero de Sequência

### ISSUE THREAD

**Issue by filiperecharte** [Ca-moes/RCOM#33]
Na application layer quando se recebe um numero de sequência que não é suposto, deve fazer-se lseek() para ir à posição certa do ficheiro escrever esse conjunto de dados.

**Comment by Ca-moes** [comment]
Ter variavel tipo L2 para ver o offset direito e não estar limitado a 256 bytes (0-255)
![image](https://user-images.githubusercontent.com/54408098/97616298-45581280-1a14-11eb-88bf-3df9db00ce92.png)
