### ISSUE TITLE
Emissor bloqueado no Read

### ISSUE THREAD

**Issue by Ca-moes** [Ca-moes/RCOM#4]
Parece que após sair do signal handler o read continua blockeado

---

Se/quando corrigirmos isto podemos deixar estar a pasta Aula 2 como está e criar uma nova pasta para fazer o resto da primeira prática laboratorial

**Comment by filiperecharte** [comment]
man signal(7):

If a signal handler is invoked while a system call or library function call is blocked, then either:
       * the call is automatically restarted after the signal handler
         returns; or
       * the call fails with the error EINTR.

Which of these two behaviors occurs depends on the interface and whether or not the signal handler was established using the SA_RESTART flag (sigaction).

write() and read() use SA_RESTART by default -> need to clear sa_flags using sigaction struct.
