### ISSUE TITLE
Coisas que acontecem 

### ISSUE THREAD

**Issue by filiperecharte** [Ca-moes/RCOM#52]
O transmitter manda um frame (113) ao qual o o receiver responde enviando um RR, esse RR não chega ao Transmitter apesar de ser enviado pelo Receiver (bytes sent: 5).
O que faz com que o Transmitter reenvie o mesmo frame (que agora é o 114) mas acontece que o programa verifica que o Control Byte não é igual ao C_I(sequenceNumber_expected) sendo um frame duplicado, envia um RR e passa ao próximo.

Receiver:
![1](https://user-images.githubusercontent.com/52135958/97790074-8ccdd280-1bbd-11eb-9acd-edcace4eea1e.png)

Transmitter:
![2](https://user-images.githubusercontent.com/52135958/97790075-8dfeff80-1bbd-11eb-8a20-9490e21d4227.png)

**Comment by filiperecharte** [comment]
não é um bug

**Comment by g-batalhao-a** [comment]
![pain](https://user-images.githubusercontent.com/50520062/97806252-9c4b2b00-1c52-11eb-94be-a5455eae49c2.png)

**Comment by Ca-moes** [comment]
> não é um bug

Era um bug

```c
do{
    attempt++;
    res = write(fd,buf,bufsize);
    tcflush(fd, TCIFLUSH);
```
O emissor escrevia e no tempo entre escrever e passar á intrução de tcflush o reader já deu parse de tudo e mandou a resposta super rápido, ficando esta resposta no lixo quando o tcflush é executado
